### ISSUE TITLE
Using the same nested binding sometime result in relation binding error

### ISSUE THREAD

**Issue by nicklayb** [nicklayb/loupe#5]
## Description

When trying to refer to the same composite binding for a relation, an error occured.

## Reproduction

Using the [example app](https://github.com/nicklayb/loupe_example), try and run the following query:

```elixir
LoupeExample.EctoDefinition.query(~s|get all Track where races.positions.driver.abbreviation = "PER" and races.positions.position = 1|)
```

## Expected behaviour

Should return Saudi Arabia and Baku, as Perez finished 1st on both these races.

## Current behaviour

The following error appears

```elixir
iex(20)> L.query(~s|get all Track where races.positions.driver.abbreviation = "PER" and races.positions.position = 1|)
** (Ecto.QueryError) deps/loupe/lib/loupe/ecto.ex:189: could not find association `driver` on schema LoupeExample.Schemas.Race in query:

from t0 in LoupeExample.Schemas.Track,
  as: :root,
  left_join: r1 in assoc(t0, :races),
  as: :a3,
  left_join: d2 in assoc(r1, :driver),
  as: :a2,
  where: d2.abbreviation == ^"PER" and r1.position == ^1,
  select: [:id, :name, :country]

    (ecto 3.10.1) lib/ecto/repo/queryable.ex:211: Ecto.Repo.Queryable.execute/4
    (ecto 3.10.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    iex:20: (file)
```

**Comment by nicklayb** [comment]
Fixed by #6
